name: build actions
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-16.04
    name: build actions with ncc
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - run: npm i -g @zeit/ncc
      - name: debug workspace
        run: env
      - name: install build-node-artifact
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/build-node-artifact
      - name: install release-mvn-pkg
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/release-mvn-pkg
      - name: install release-prepare-mvn-pkg
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/release-prepare-mvn-pkg
      - name: install release-verify-auto-deploy
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/release-verify-auto-deploy
      - name: install verify-mvn-dependencies
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/verify-mvn-dependencies
      - name: commit ncc build in bidrag-actions
        uses: Endbug/add-and-commit@v2.3.0
        with:
          message: "Fresh build of actions using npm and ncc by ${{ github.actor }}"
          path: "."
          pattern: "."
          force: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
